# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'zonegen', '0001_initial'), (b'zonegen', '0002_auto_20161130_0454'), (b'zonegen', '0003_auto_20161130_0517'), (b'zonegen', '0004_auto_20161130_0525'), (b'zonegen', '0005_auto_20161130_0532')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
