# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zid', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
