# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonegen', '0001_squashed_0005_auto_20161130_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
