language: python

services: postgresql

before_install:
  - export PYTHONPATH=$HOME/builds/thecristen/zone-vision
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt --quiet

before_script:
  - psql -c "CREATE DATABASE travisci" -U postgres
  - psql -c "CREATE EXTENSION postgis" -d travisci

script:
  - python manage.py test
  - pylint zonegen --load-plugins=pylint_django
